<?php echo $this->form()->openTag($form) ?>

    <fieldset>

		<legend>Cadastro de Filmes</legend>

	<div class="row-fluid">
		<div class="control-group col-md-4">
			<label class="control-label"><?php echo $this->formLabel($form->get('filmes_nome')); ?></label>
			<div class="controls">
			<?php echo $this->formElement($form->get('filmes_nome')); ?>
			<p class="help-block"><?php echo $this->formElementErrors($form->get('filmes_nome')); ?></p>
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="control-group col-md-4">
			<label class="control-label"><?php echo $this->formLabel($form->get('filmes_foto')); ?></label>
			<div class="controls">
			<?php echo $this->formElement($form->get('filmes_foto')); ?>
			<p class="help-block"><?php echo $this->formElementErrors($form->get('filmes_foto')); ?></p>
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="control-group col-md-4">
			<label class="control-label"><?php echo $this->formLabel($form->get('filmes_preco')); ?></label>
			<div class="controls">
			<?php echo $this->formElement($form->get('filmes_preco')); ?>
			<p class="help-block"><?php echo $this->formElementErrors($form->get('filmes_preco')); ?></p>
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="control-group col-md-12">
			<div class="controls">
			<?php echo $this->formElement($form->get('filmes_status')); ?> <label class="control-label"><?php echo $this->formLabel($form->get('filmes_status')); ?></label>
			<p class="help-block"><?php echo $this->formElementErrors($form->get('filmes_status')); ?></p>
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="control-group col-md-12">
			<label class="control-label"><?php echo $this->formLabel($form->get('filmes_descricao')); ?></label>
			<div class="controls">
			<?php echo $this->formElement($form->get('filmes_descricao')); ?>
			<p class="help-block"><?php echo $this->formElementErrors($form->get('filmes_descricao')); ?></p>
			</div>
		</div>
	</div>

	<div id="btn-fim">
		<?php echo $this->formElement($form->get('submit')); ?>
	</div>

</form>



<?php echo $this->form()->closeTag($form) ?>