<?php if (count($messages)) : ?>
	<?php foreach ($messages as $value) :
			$key = key($value);
			$message = current($value);
	?>
		<div class="alert alert-<?php echo $key; ?> alert-dismissible" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		  <?php echo $message; ?>
		</div>
	<?php endforeach; ?>
<?php endif; ?>

<h1><?php echo $title; ?></h1>

<div class="row col-md-12" style="padding-bottom: 10px;">
	<a href="/filmes/novo" class="btn btn-primary">Novo</a>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Foto</th>
      <th>Filme</th>
      <th>Categoria</th>
      <th>Valor Aluguel</th>
	  <th>Opções</th>
    </tr>
  </thead>
  <tbody>
	<?php if (count($filmes)) :
	     foreach ($filmes as $filme): ?>
        <tr>
          <th scope="row"><?php echo $filme->filmes_id;?></th>
          <?php if ($filme->filmes_foto == null):?>
          	<td>Sem cartaz</td>
          <?php else:?>
          	<td><img src="/conteudo/filmes/<?php echo $filme->filmes_foto;?>" width="100"></td>
          <?php endif;?>
          <td><?php echo $filme->filmes_nome; ?></td>
          <td><?php echo $this->utilHelper()->getCategoryName($filme->categoria_id); ?></td>
          <td><?php echo $filme->filmes_preco; ?></td>
          <td>
  		      <a href="/filmes/editar/<?php echo $filme->filmes_id;?>" title="Editar"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
  		      <a href="/filmes/remove/<?php echo $filme->filmes_id;?>" title="Excluir"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
          </td>
        </tr>
    <?php endforeach;
        else: ?>
	        <tr>
	          <th scope="row" colspan='5'>Nenhum filme cadastrado!</th>
	        </tr>
        <?php endif;?>
  </tbody>
</table>

<?php echo $this->paginationControl($filmes, 'Sliding', 'partials/paginator/control.phtml'); ?>