<?php if (count($messages)) : ?>
	<?php foreach ($messages as $value) :
			$key = key($value);
			$message = current($value);
	?>
		<div class="alert alert-<?php echo $key; ?> alert-dismissible" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		  <?php echo $message; ?>
		</div>
	<?php endforeach; ?>
<?php endif; ?>

<h1><?php echo $title; ?></h1>

<div class="row col-md-12" style="padding-bottom: 10px;">
	<a href="/categoria/novo" class="btn btn-primary">Novo</a>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Categoria</th>
	  <th>Opções</th>
    </tr>
  </thead>
  <tbody>
	<?php if (count($categoria)) :
	     foreach ($categoria as $filme): ?>
        <tr>
          <th scope="row"><?php echo $filme->categoria_id;?></th>
          <td><?php echo $filme->categoria_nome;?></td>
          <td>
		      <a href="/categoria/editar/<?php echo $filme->categoria_id;?>" title="Editar"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
		      <a href="/categoria/remove/<?php echo $filme->categoria_id;?>" title="Excluir"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
          </td>
        </tr>
    <?php endforeach;
        else: ?>
	        <tr>
	          <th scope="row" colspan='5'>Nenhuma categoria cadastrado!</th>
	        </tr>
        <?php endif;?>
  </tbody>
</table>

<?php echo $this->paginationControl($categoria, 'Sliding', 'partials/paginator/control.phtml'); ?>